import{S as f,i as m}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function o(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();const d=document.querySelector("form"),a=document.querySelector("input"),l=document.querySelector(".gallery"),c=document.querySelector(".loader-container"),u=new f(".gallery a",{aptions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250});u.on("show.simplelightbox");d.addEventListener("submit",i=>{i.preventDefault();const r=a.value;a.value="",l.innerHTML="",y(r)});function y(i){p();const s=`https://pixabay.com/api/?key=42469788-7d7013196b534fb1bad6f4ac3&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`;fetch(s).then(o=>{if(o.ok)return o.json();throw new Error(o.status)}).then(o=>{if(o.hits.length===0)m.error({timeout:1e3,message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const t=o.hits.map(e=>`
                <li class="gallery-item"><a href="${e.largeImageURL}">
                <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
                <ul class="gallery-image-data">
                <li class="data-quantity"><b>Likes </b>${e.likes}</li>
                <li class="data-quantity"><b>Views </b>${e.views}</li>
                <li class="data-quantity"><b>Comments </b>${e.comments}</li>
                <li class="data-quantity"><b>Downloads </b>${e.downloads}</li>
                </ul>
                </li>`).join("");l.insertAdjacentHTML("beforeend",t),u.refresh()}}).catch(o=>{console.log(o)}).finally(()=>{g()})}function p(){c.style.display="flex"}function g(){c.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
